package learningJava;
import java.util.Scanner;

public class ScannerInput {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//	System.out.println("Enter a number:");
//	Scanner scanner = new Scanner(System.in);
//	int number = scanner.nextInt();
//	System.out.println("Number entered is: "+ number);
//	scanner.close();	
	
//	System.out.println("Enter a floating number:");
//	Scanner scanner = new Scanner(System.in);
//	float number = scanner.nextFloat();
//	System.out.println("Number entered is: "+ number);
//	scanner.close();
		
		System.out.println("Enter a Float:");
		Scanner scanner = new Scanner(System.in);
		float number1 = scanner.nextFloat();
		scanner.nextLine(); // Consume the newline character
		System.out.println("Enter a String:");
		String strVariable1 = scanner.next();
		System.out.println("String entered is: " + strVariable1);
		scanner.close();
	
		
	
//		after reading a float using scanner.nextFloat(), the newline character (\n) generated by pressing Enter after entering the float value is still in the input buffer.

//		When you subsequently call scanner.nextLine(), it reads this newline character and returns an empty string. This is because nextLine() consumes the newline character left over 
//		from the previous input and then reads the rest of the input until the end of the line, which is an empty string in this case.
		
	}

}
